baseURL = 'https://randomgeekery.life'

languageCode = 'en-us'
theme = "hyde-ish"
title = 'Random Geekery Life'

[markup.goldmark.renderer]
unsafe = true

[menus]
main = [
  {Name = "RSS", URL = "/index.xml"},
  {Name = "Random Geekery", URL = "https://randomgeekery.org" },
  {Name = "@brianwisti", URL = "https://twitter.com/brianwisti" },
  {Name = "randomgeek@hackers.town", URL = "https://hackers.town/@randomgeek"}
]

[params]
description = 'A tumblelog by Brian Wisti'
PlausibleDomain = "randomgeekery.life"
