baseURL = 'https://randomgeekery.life'

languageCode = 'en-us'
theme = "hyde-ish"
title = 'Random Geekery Life'

[markup.goldmark.renderer]
unsafe = true

[menus]
main = [
  {Name = "RSS", URL = "/index.xml"},
  {Name = "Source Repo", URL = "https://github.com/brianwisti/rg-life"}
]

[params]
description = 'A tumblelog by Brian Wisti'
PlausibleDomain = "randomgeekery.life"
Me = [
  {Name = "Github", URL = "https://github.com/brianwisti" },
  { Name = "@randomgeek@hackers.town", URL = "https://hackers.town/@randomgeek" },
  {Name = "Random Geekery", URL = "https://randomgeekery.org" }
]
